name: Go
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version-file: 'go.mod'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Change Go path
        run: export GOPATH=$PWD
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        run: go test ./...
      - name: Install Win
        run: env GOOS=`windows` GOARCH=`386` go build -o ./release/telegramBot.exe  | ls
      - name: Install Pi
        run: env GOOS=`linux` GOARCH=`arm` go build -o ./release/telegramBot  | ls
      - name: Get  artifacts
      - name: Get  artifacts
        uses: actions/upload-artifact@v1
        with:
          name: telegramBot
          path: ./release
